package edu.pitt.cs;
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;


@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tESTFIXTURE() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
    
  }
  @Test
  public void tEST1LINKS() {
      driver.get("http://localhost:8080/reset");
      driver.findElement(By.linkText("Reset")).click();
  
      String currentUrl = driver.getCurrentUrl();
      assertThat(currentUrl, is("http://localhost:8080/reset")); // Ensure it points to the right URL
  }
  
  @Test
  public void tEST2RESET() {
      driver.get("http://localhost:8080/rent-a-cat");
      js.executeScript("document.cookie = '1=true'; document.cookie = '2=true'; document.cookie = '3=true';");
      driver.findElement(By.linkText("Reset")).click();
  
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//li[text()='ID 1. Jennyanydots']")));
  
      assertThat(driver.findElements(By.xpath("//li[text()='ID 1. Jennyanydots']")).size(), is(not(0)));
      assertThat(driver.findElements(By.xpath("//li[text()='ID 2. Old Deuteronomy']")).size(), is(not(0)));
      assertThat(driver.findElements(By.xpath("//li[text()='ID 3. Mistoffelees']")).size(), is(not(0)));
  }
  
  @Test
  public void tEST3CATALOG() {
      driver.get("http://localhost:8080/");
      driver.findElement(By.linkText("Catalog")).click();

      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("(//img)[2]")));

      String imgSrc = driver.findElement(By.xpath("(//img)[2]")).getAttribute("src");

      assertThat(imgSrc, is("http://localhost:8080/images/cat2.jpg"));
  }

  @Test
  public void tEST4LISTING() {
    // driver.get("http://localhost:8080/");
    // driver.findElement(By.xpath("//a[text()=\'Catalog\']")).click();
    // {
    //   List<WebElement> elements = driver.findElements(By.xpath("//li"));
    //   assert(elements.size() > 0);
    // }
    // {
    //   List<WebElement> elements = driver.findElements(By.xpath("//li[text()=\'ID 3. Mistoffelees\']"));
    //   assert(elements.size() > 0);
    // }
    driver.get("http://localhost:8080/");

    driver.findElement(By.linkText("Catalog")).click();

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]")));

    WebElement thirdCatElement = driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[3]"));

    String thirdCatText = thirdCatElement.getText();

    assertEquals("ID 3. Mistoffelees", thirdCatText);
  }

  @Test
  public void tEST5RENTACAT() {
    driver.get("http://localhost:8080/");
    driver.get("http://localhost:8080/rent-a-cat");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\'Rent\']"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\'Return\']"));
      assert(elements.size() > 0);
    }
  }

  // @Test
  // public void tEST6RENT() {
  //   driver.get("http://localhost:8080/");
  //   driver.get("http://localhost:8080/rent-a-cat");
  //   driver.findElement(By.id("rentID")).click();
  //   driver.findElement(By.id("rentID")).sendKeys("1");
  //   driver.findElement(By.xpath("//button[text()=\'Rent\']")).click();
  //   {
  //     List<WebElement> elements = driver.findElements(By.xpath("//li[text()=\'Rented out\']"));
  //     assert(elements.size() > 0);
  //   }
  //   {
  //     List<WebElement> elements = driver.findElements(By.xpath("//li[text()=\'ID 2. Old Deuteronomy\']"));
  //     assert(elements.size() > 0);
  //   }
  // }
  @Test
  public void tEST6RENT() {
      driver.get("http://localhost:8080/");
  
      driver.findElement(By.linkText("Rent-A-Cat")).click();
  
      driver.findElement(By.id("rentID")).sendKeys("1");
      driver.findElement(By.xpath("//button[text()='Rent']")).click();
  
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("/html/body/div/main/div[1]")));
  
      WebElement firstItemElement = driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[1]"));
      String firstItemText = firstItemElement.getText();
      assertEquals("Rented out", firstItemText);
  
      WebElement secondItemElement = driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[2]"));
      String secondItemText = secondItemElement.getText();
      assertEquals("ID 2. Old Deuteronomy", secondItemText);
  
      WebElement thirdItemElement = driver.findElement(By.xpath("/html/body/div/main/div[1]/div/ul/li[3]"));
      String thirdItemText = thirdItemElement.getText();
      assertEquals("ID 3. Mistoffelees", thirdItemText);
  }
  
  


  @Test
  public void tEST10GREETACAT() {
      driver.get("http://localhost:8080/");
      driver.findElement(By.linkText("Greet-A-Cat")).click();
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#greeting > h4")));

      String greetingText = driver.findElement(By.cssSelector("#greeting > h4")).getText();
      System.out.println("The greeting text is: " + greetingText); 
      assertThat(greetingText, is("Meow!Meow!Meow!")); 
  }

  @Test
  public void tEST11GREETACATWITHNAME() {
      driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#greeting > h4")));

      String greetingText = driver.findElement(By.cssSelector("#greeting > h4")).getText();
      System.out.println("The greeting text is: " + greetingText); 

      assertThat(greetingText, is("Meow! from Jennyanydots.")); 
  }

//   @Test
//   public void dEFECT1FUNFEED() {
//     driver.get("http://localhost:8080/");
//     driver.get("http://localhost:8080/feed-a-cat");
//     driver.findElement(By.id("catnips")).sendKeys("-3");
//     driver.findElement(By.xpath("//button[text()=\'Feed\']")).click();
//     {
//       List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'feedResult\' and text()=\'Cat fight!\']"));
//       assert(elements.size() > 0);
//     }
//   }

//   @Test
//   public void dEFECT2FUNGREETACAT() {
//     driver.get("http://localhost:8080/");
//     driver.get("http://localhost:8080/greet-a-cat");
//     {
//       List<WebElement> elements = driver.findElements(By.cssSelector("#greeting > h4"));
//       assert(elements.size() > 0);
//     }
//     driver.get("http://localhost:8080/rent-a-cat");
//     driver.findElement(By.id("rentID")).sendKeys("1");
//     driver.findElement(By.xpath("//button[text()=\'Rent\']")).click();
//     driver.get("http://localhost:8080/greet-a-cat");
//     {
//       List<WebElement> elements = driver.findElements(By.xpath("//div[text()=\'Meow!Meow!\']"));
//       assert(elements.size() > 0);
//     }
//   }

//   @Test
//   public void dEFECT3FUNGREETACATWITHNAME() {
//     driver.get("http://localhost:8080/");
//     js.executeScript("document.cookie = \"3=true\";");
//     driver.get("http://localhost:8080/greet-a-cat/Mistoffelees");
//     {
//       List<WebElement> elements = driver.findElements(By.xpath("//div[text()=\'Mistoffelees is not here.\']"));
//       assert(elements.size() > 0);
//     }
//   }

  @Test
  public void tEST9FEED() {
    driver.get("http://localhost:8080/");
    driver.get("http://localhost:8080/feed-a-cat");
    driver.findElement(By.id("catnips")).sendKeys("6");
    driver.findElement(By.xpath("//button[text()=\'Feed\']")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\'feedResult\' and text()=\'Nom, nom, nom.\']")));
    }
  }

  @Test
  public void tEST8FEEDACAT() {
    driver.get("http://localhost:8080/");
    driver.get("http://localhost:8080/feed-a-cat");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[text()=\'Feed\']"));
      assert(elements.size() > 0);
    }
  }

  @Test
  public void tEST7RETURN() {
    driver.get("http://localhost:8080/");
    js.executeScript("document.cookie = \"2=true\";");
    driver.get("http://localhost:8080/rent-a-cat");
    driver.findElement(By.id("returnID")).sendKeys("2");
    driver.findElement(By.xpath("//button[text()=\'Return\']")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[text()=\'ID 1. Jennyanydots\']"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[text()=\'ID 2. Old Deuteronomy\']"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//li[text()=\'ID 3. Mistoffelees\']"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'returnResult\' and text()=\'Success!\']"));
      assert(elements.size() > 0);
    }
  }
}